// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RolodexApp.Data;

#nullable disable

namespace RolodexApp.Migrations
{
    [DbContext(typeof(RolodexContext))]
    [Migration("20241119185325_AddingSeedPersons")]
    partial class AddingSeedPersons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolodexApp.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Email = "jesse@jesse.com",
                            FirstName = "Jesse",
                            LastName = "Harlan",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            PersonId = 2,
                            Address1 = "123 Someplace Ln",
                            City = "No Place",
                            FirstName = "Tom",
                            LastName = "Jones",
                            PhoneNumber = "1234567891",
                            PostalCode = "12345",
                            State = "NY"
                        },
                        new
                        {
                            PersonId = 3,
                            Address1 = "123 Someplace Ln",
                            City = "No Place",
                            FirstName = "Sue",
                            LastName = "Jones",
                            PhoneNumber = "1234567892",
                            PostalCode = "12345",
                            State = "NY"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
